### ISSUE TITLE
Withdrawn players should be highlighted in edit rosters

### ISSUE THREAD

**Issue by tnan123** [Lichess4545/heltour#196]
We move players from the unassigned pool to the alternate pool throughout the season and sometimes it is difficult to remember if someone should be left in the unassigned pool.

Looking at registration date sometimes doesn't help as sometimes people don't join slack until much later. We've been making comments on the players to remind us. 

I suggest they could be highlighted with the red mark as those "not in slack" are currently highlighted.

**Comment by hopffgam** [comment]
With #466 a comment is added automatically to withdrawn players, and that comment can be seen on the Edit Rosters view
