### ISSUE TITLE
Include captains in pairings message

### ISSUE THREAD

**Issue by kvackkvackanka** [Lichess4545/heltour#223]
Suggestion from season 12 survey: "Have chesster include the captains in every "scheduling thread" it creates. That way we can keep on top of problems without having to bother our teammates about it. It can be really frustrating when you only get hearsay about some conflict that's happening during scheduling."

Moved from: https://github.com/endrawes0/Chesster/issues/282

**Comment by glbert-does** [comment]
i talked to the current team mods, and they do not think this feature is needed for now. can always reopen if opinions should change in 6 years or so.
