### ISSUE TITLE
Modify late contact logic for changed pairings

### ISSUE THREAD

**Issue by cyanfish** [Lichess4545/heltour#226]
Ideally this would work with both alternates and re-pairings (in lonewolf).

Possibly use ScheduledNotification (created/updated whenever a pairing's players change) for timing, instead of a centralized task. Performance would be an issue if they are all running at slightly different times, but if we round to the nearest hour they should all have the same time, and run_scheduled_events would run them all at once in a loop without the overhead of a separate celery task execution.

Or there might be a better way to do it.

**Comment by glbert-does** [comment]
i believe the late contact logic was fixed a while ago. at least i am not aware of any current issues, other than with the indicators on the pairing page, which is an independent issue.
