### ISSUE TITLE
Set player available if a game is scheduled

### ISSUE THREAD

**Issue by kvackkvackanka** [Lichess4545/heltour#236]
While an alt search is in progress, the player is still on the pairing and can schedule a game. This does not cancel the alt search. If an alt is subsequently found, the previous game scheduling will be removed (and the alt can schedule). In particular, this has happened when a player is automatically set unavailable after 24h but quickly schedules the game after that, and forgets to update their availability status.

Two solutions:

a) If a game is scheduled, set the player available for that week. This cancels the alt search. 
b) Only allow available players to schedule. (Trigger chesster message when trying to schedule.)

**Comment by lakinwecker** [comment]
This means that an opponent could maliciously set the date, and chesster would stop searching for a pairing. Is that situation better than the current situation?

**Comment by glbert-does** [comment]
i think this would indeed be preferable. the situation described happens often, several times per season. the situation described by lakinwecker requires malice. also, solution (b) wouldn't even make the malicious act possible.
