### ISSUE TITLE
Remove `Register` section and button in home league page when a player is already in the league. 

### ISSUE THREAD

**Issue by lenguyenthanh** [Lichess4545/heltour#269]
When a player is a full time or alternative player in a league which is running. There is no reason to show register button in the home page.

Those red circled parts are objects to remove.
![screenshot 2018-11-30 at 18 56 09](https://user-images.githubusercontent.com/437967/49307327-1dcd3800-f4d5-11e8-8942-a918dc3f007a.png)

![screenshot 2018-11-30 at 19 23 29](https://user-images.githubusercontent.com/437967/49307504-ac41b980-f4d5-11e8-81f5-5761dd009174.png)

**Comment by colwem** [comment]
I got this fam.
