### ISSUE TITLE
Include UTC offsets for players in pairing notifications for 4545 league

### ISSUE THREAD

**Issue by swandog30** [Lichess4545/heltour#272]
Pairings for Lonewolf **include** the UTC offset for the players:
> @swandog (_white pieces_, UTC-06:00) vs @Kyle Barry (_black pieces_, UTC-08:00)

Pairings for 4545 **don't include** the UTC offset for the players:
> @halloway (_white pieces_) vs @swandog (_black pieces_)

It seems like this occurs when the pairing involves alternates.  @lakinwecker found the issue in the codebase:

Times aren't included here: https://github.com/cyanfish/heltour/blob/master/heltour/tournament/notify.py#L324-L340

Times are included here:
https://github.com/cyanfish/heltour/blob/master/heltour/tournament/notify.py#L446-L463

**Comment by nicwest** [comment]
I believe we already have this functionality
![Screenshot 2024-12-01 at 15 25 50](https://github.com/user-attachments/assets/30d742ce-5b3e-41fb-8315-40cf4e65a081)

**Comment by glbert-does** [comment]
agreed.
