### ISSUE TITLE
Dark Mode standings text is unreadable in lonewolf FAQ

### ISSUE THREAD

**Issue by lakinwecker** [Lichess4545/heltour#310]
https://i.imgur.com/XOTPAIy.png

We should fix these.

**Comment by cyanfish** [comment]
I fixed it temporarily but the formatting will be removed next edit. We will need to do this for a permanent fix: https://stackoverflow.com/a/15659962/2112909

**Comment by nicwest** [comment]
I think this can be closed with #348
