### ISSUE TITLE
Preview e-mails before sent

### ISSUE THREAD

**Issue by colwem** [Lichess4545/heltour#311]
Before admin actions that will cause a message to be sent, display that message for the admin first.  I just sent out a bunch of e-mails that were not correct because I couldn't first preview what they were going to say.

Namely the season had "begun"  so it told everyone they would be an alternate.  When really. we just forgot to change the start date of the season.  I didn't realize that was going to happen before I hit the "approve" button.

For instance on the `admin/tournament/registration/{id}/review/` page. have a preview of the e-mails that will be sent displayed on that page at the bottom.

**Comment by glbert-does** [comment]
i think this one should be "wontfix":
first, the email currently only is saying that they will "probably" be an alternate.
second, if you're accepting registrations while still intending to change the start date, you already gave the players wrong information that is way more important than whether they'll be an alt or on a team. namely the date when they should be ready to play.
third, there's no way you keep reading those email previews anyway. you'd do it for the first couple of accounts you approve maybe, but once you have approved a hundreds, there's no way in hell you'd even look at it.
so to me this feels like something where the solution should be to have mods pay more attention how they set up the season.
