### ISSUE TITLE
Setting availability with Change Registration form

### ISSUE THREAD

**Issue by hopffgam** [Lichess4545/heltour#409]
In the registration form you can provide weeks you are unavailable. However, when you do that on the registration form after your registration had been approved already, this will only switch weeks from available to unavailable. Changing a week from unavailable to available will not be registered in the database.

Instead of fixing that particular issue I would be in favor of removing the possibility to set availabilities in the registration form after a registration had been approved already. Once a registration is approved players can use Edit Availability instead.

**Comment by glbert-does** [comment]
potentially easier could be to disallow editing of registrations once the season has started. at least i cannot think of any reason that would make editing the registration at all useful after the season start.
