### ISSUE TITLE
add bolded instruction to registration form re: non-provisional classical

### ISSUE THREAD

**Issue by pawnsandprawns** [Lichess4545/heltour#447]
on our registration page, I think we should have in bold:

**Applications are only processed _after_ playing enough classical games to establish a non-provisional rating.  If there is a question mark next to your classical rating, your application will not be processed.**

**Comment by lakinwecker** [comment]
That's only true for Lonewolf though. I think the team league will sometimes approve people before that point. It would need to be league specific

**Comment by pawnsandprawns** [comment]
As per our discussion on slack, I think the following two points were established:

+ league-specific warnings sound good, the above warning could be for the 4545 team league registration instead of the current warning: "If it is provisional, it must be established ASAP by playing more games."

+ an automated reminder email, sent a week after registration to applicants that are still provisional, would be great.  Wording could be: "Thank you for applying to the Lichess <4545 Team League/insert League here>.  As stated at registration, your application will be reviewed once your classical rating is established.  To do this, play more classical games until there is no question mark next to the rating."

Other points that were discussed but it's unclear to me if they were decided:

+ A "everything-but-established-rating" status for applications, and an email response of "Approved pending established rating," and then an automated upgrade to "approved" for applications that then establish the rating.  I don't like the idea of committing mods to reviewing applications that may never get an established rating at all, but I think the other leagues are interested.

+ A different response for form submission with "no" selected for established rating, perhaps a pop-up warning by the box when selected, or a warning page, etc.  I think the consensus on this was to wait and see how these other changes do first.

Possible issue:
- How should the system handle applications that just reach established, but then slip back into provisional before final acceptance?
