### ISSUE TITLE
Add a link to a players lichess opening book under players profile link

### ISSUE THREAD

**Issue by TBestLittleHelper** [Lichess4545/heltour#456]
On a 4545 profile, https://www.lichess4545.com/team4545/season/32/player/tbest/ , there is a link to a players lichess profile.
I suggest also having a link directly to the players opening book. : https://lichess.org/analysis#explorer/TBest

Motivation is to save 1 click, as checking someone's opening book is common in 4545.

**Comment by glbert-does** [comment]
maybe instead the existing link on the pairing page for downloading a pgn should be replaced? not sure anyone still uses these.

**Comment by MattMaginniss** [comment]
Went with adding the Opening book to the pairings rather than removing the download games button. (https://github.com/Lichess4545/heltour/pull/503)

Would be more than happy to alter this if you think the two icons are too busy/cramped. If you all like it, then I am happy with the result.

**Comment by timothyha** [comment]
This change is too opening-centric.  Games are objective and full truth about how a player plays, but the opening book is opening-centric.  Clicking on 4545 name we get to see the Lichess profile link and can go from there anyway

**Comment by glbert-does** [comment]
this can be closed, right? i will just do it.
